[package]
name = "network_sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34.0"
clap = "4.5.3"
log = "0.4.14"
env_logger = "0.11.3"